on:
  push: 
    branches: main
    
jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: packing
        shell: bash
        run: |
          cmake -H. -B_build -DCPACK_GENERATOR="TGZ"
          cmake --build _build --target package
          
          
      - uses: actions/checkout@v2   
      - uses: actions/relese-action@v1
        with:
          tag: v0.0.0.1
          token: ${{ secrets.GITHUB_TOKEN }}
